# Generated by Django 3.0 on 2022-03-12 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
