# Generated by Django 3.0 on 2022-03-21 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220321_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileeducationtutor',
            old_name='username',
            new_name='user',
        ),
    ]
