# Generated by Django 3.0 on 2022-03-23 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20220323_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='major',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='school',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='schoolProgram',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='schoolYear',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='university',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='universityYear',
        ),
        migrations.CreateModel(
            name='ProfileEducationTutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('schoolProgram', models.CharField(blank=True, max_length=100, null=True)),
                ('schoolYear', models.CharField(blank=True, max_length=4, null=True)),
                ('university', models.CharField(blank=True, max_length=100, null=True)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('faculty', models.CharField(blank=True, max_length=100, null=True)),
                ('major', models.CharField(blank=True, max_length=100, null=True)),
                ('universityYear', models.CharField(blank=True, max_length=4, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Profile')),
            ],
        ),
    ]
