# Generated by Django 3.0 on 2022-03-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20220323_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='idcard',
            field=models.ImageField(blank=True, default='profilePic/idcard.jpg', null=True, upload_to='profilePic/'),
        ),
    ]
