# Generated by Django 3.0 on 2022-03-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_yourself'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Yourself',
            new_name='YourselfTutor',
        ),
    ]
