# Generated by Django 3.0 on 2022-03-26 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
