# Generated by Django 3.0 on 2022-03-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='approve',
            field=models.BooleanField(default=False, verbose_name='Approve'),
        ),
    ]
