# Generated by Django 3.0 on 2022-03-27 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_course_introduce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='introduce',
            new_name='introduceTutor',
        ),
    ]
