# Generated by Django 3.0 on 2022-03-27 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20220327_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProfileEducationTutor'),
        ),
    ]
