# Generated by Django 3.0 on 2022-03-30 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_event_courseprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='coursePrice',
        ),
    ]
