# Generated by Django 3.0 on 2022-04-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseDay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='courseTime',
            field=models.TimeField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
