# Generated by Django 3.0 on 2022-04-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20220403_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourselftutor',
            name='facebook',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='yourselftutor',
            name='line',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseDay',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
