# Generated by Django 3.0 on 2022-04-06 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20220407_0031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyCourse',
            new_name='MyCourseStudent',
        ),
        migrations.CreateModel(
            name='MyCourseTutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takeBy', models.CharField(max_length=100)),
                ('courseId', models.IntegerField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Profile')),
            ],
        ),
    ]
