# Generated by Django 3.0 on 2022-04-08 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20220407_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycoursetutor',
            name='takeBy',
        ),
        migrations.AddField(
            model_name='mycoursetutor',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.MyCourseStudent'),
        ),
    ]
