# Generated by Django 3.0 on 2022-04-08 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20220408_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycoursetutor',
            name='course',
        ),
        migrations.RemoveField(
            model_name='mycoursetutor',
            name='user',
        ),
    ]
