# Generated by Django 3.0 on 2022-04-08 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20220408_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycoursetutor',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Course'),
        ),
    ]
