# Generated by Django 3.0 on 2022-04-08 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_mycoursetutor_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycoursetutor',
            name='course',
        ),
        migrations.RemoveField(
            model_name='mycoursetutor',
            name='courseId',
        ),
    ]
