# Generated by Django 3.0 on 2022-04-08 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20220408_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycoursetutor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Profile'),
        ),
    ]
