# Generated by Django 3.0 on 2022-04-08 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_mycoursetutor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycoursetutor',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Course'),
        ),
        migrations.AddField(
            model_name='mycoursetutor',
            name='courseId',
            field=models.IntegerField(null=True),
        ),
    ]
