# Generated by Django 3.0 on 2022-04-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20220408_1616'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyCourseTutor',
        ),
    ]
