# Generated by Django 3.0 on 2022-04-08 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_mycoursetutor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyCourseTutor',
        ),
    ]
