# Generated by Django 3.0 on 2022-04-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_delete_mycoursetutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycoursestudent',
            name='finish',
            field=models.BooleanField(default=False, verbose_name='Finish'),
        ),
    ]
