# Generated by Django 3.0 on 2022-04-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20220409_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='star',
            field=models.BooleanField(default=False),
        ),
    ]
