# Generated by Django 3.0 on 2022-04-11 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_rating_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Course'),
        ),
    ]
