# Generated by Django 3.0 on 2022-04-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_mycoursestudent_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='courseId',
            field=models.IntegerField(null=True),
        ),
    ]
