# Generated by Django 3.0 on 2022-04-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_profile_userrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='userRating',
        ),
        migrations.AddField(
            model_name='course',
            name='userRating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True),
        ),
    ]
