# Generated by Django 3.0 on 2022-04-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_auto_20220413_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='userRating',
            new_name='courseRating',
        ),
    ]
