# Generated by Django 3.0 on 2022-04-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_auto_20220413_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
