# Generated by Django 3.0 on 2022-04-19 12:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_auto_20220419_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, default='profilePic/avatarPic.jpg', max_length=255, null=True, verbose_name='photo'),
        ),
    ]
