# Generated by Django 3.0 on 2022-04-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_auto_20220419_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='idcard',
            field=models.ImageField(blank=True, default='profilePic/idcard.jpg', null=True, upload_to='idCard/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='profilePic/avatarPic.jpg', null=True, upload_to='profilePic/'),
        ),
        migrations.AlterField(
            model_name='yourselftutor',
            name='video',
            field=models.FileField(blank=True, default='#.mp4', null=True, upload_to='Video/'),
        ),
    ]
