# Generated by Django 3.0 on 2022-04-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_auto_20220419_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='idcard',
            field=models.ImageField(blank=True, default='idCard/idcard_midixi.jpg', null=True, upload_to='idCard/'),
        ),
    ]
