# Generated by Django 3.0 on 2022-04-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_auto_20220419_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourselftutor',
            name='facebook',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='yourselftutor',
            name='line',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
