# Generated by Django 3.2.8 on 2022-04-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_auto_20220424_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileeducationtutor',
            name='degree',
        ),
    ]
